### ISSUE TITLE
Include Multilevel Radix-Heap

### ISSUE THREAD

**Issue by manpen** [tlx/tlx#10]
For a project we needed a fast multi-level radix heap (i.e., rather than operating on the binary representation of an integer, we use its R-ary representation). This increases the number of buckets in the data structure but reduces the number of moves an item has to go through.

While the implementation is currently tailored towards our application, I think it makes sense to make it a general purpose radix heap. Are you interested to include it into TLX? If so, I would prepare a PR in near future.

**Comment by bingmann** [comment]
Moritz @MoKoB also had a radix heap implementation.
about including: yes, if it is well tested.

**Comment by manpen** [comment]
The PQ has quite a few test cases and is currently used in our Curveball implementation. So I feel quite confident that works fine. I'm currently cleaning up the code and refactor it to tlx/stl naming conventions.

There are two sub-modules which could be useful for other applications:
- "Rank of integers" computes the rank of a signed/unsigned integer (so basically conversion to unsigned but keeping the relative order elements, i.e. std::numeric_limits<T>::min() is always mapped to 0 and so on)
https://github.com/manpen/tlx/tree/feature_integer_rank

- "Bitarray" (need a better name): the main purpose of the data structure is to find the smallest bit set in a bit field of templated size. We can update each bit individually. It's implemented as a high-fanout (64) search tree and uses low-level bit operations such as tlx::ffs.
https://github.com/manpen/tlx/tree/feature_bitarray

Both module have separate tests cases, and so it makes sense to put them into seperate header file. But if you consider them not useful, I will simply put them into the PQ's detail namespace.

Questions:
- Should I put them into the radixheap header file, or keep them separate?
- Does it make sense to add a folder "datastructures"/"containers" to avoid messing up tlx's root folder?

**Comment by bingmann** [comment]
Q:
- Does it make sense to add a folder "datastructures"/"containers" to avoid messing up tlx's root folder?

I have been thinking about this. The answer is yes. But `tlx/data_structure/btree_set.hpp`  is too long, and container is wrong for loser_tree.hpp

Any other ideas?

**Comment by manpen** [comment]
I would not use `data_structures` since its unclear whether you write it with underscore or as a single word ... Why not use `container`? I think `tlx/container/btree_set.hpp` is not too bad and it's shorter than most files in `algorithm`

**Comment by bingmann** [comment]
And overlook the weirdness with temporary data structures such as the loser tree.

**Comment by bingmann** [comment]
Let's do the container.

**Comment by bingmann** [comment]
Merged in pull request #12
