### ISSUE TITLE
btree_map uses deprecated / removed allocator member rebind::other

### ISSUE THREAD

**Issue by niclar** [tlx/tlx#37]
Hi compiling in C++20 the rebind::other member in the std::allocator is deprecated in C++17 and removed in C++20 hence rendering the compilation error below.

btree.hpp(275,64): error C2039: 'other': is not a member of 'std::allocator<std::pair<Key_,Data_>>'

-Any plans on making this library C++20 compatible ?

-If nothing else the above is solved by using a custom backwards compatible allocator

**Comment by bingmann** [comment]
This should be fixed by now in the master branch.
Which compiler is this error from?

**Comment by niclar** [comment]
vs2022 /std:c++latest

I can confirm it works now.

Thanks
